program Manufacture_Timber_BMI;

uses
  Forms,
  Ioctl in '..\..\Modul General\Library\Ioctl.pas',
  untConstanta in '..\..\Modul General\Library\untConstanta.pas',
  untFastReport in '..\..\Modul General\Library\untFastReport.pas',
  untInitVCL in '..\..\Modul General\Library\untInitVCL.pas',
  untProcedure in '..\..\Modul General\Library\untProcedure.pas',
  untZetronServer in '..\..\Modul General\Library\untZetronServer.pas',
  dtmGlobal in '..\..\Modul General\Data Module Global\dtmGlobal.pas' {dmGlobal: TDataModule},
  dtmInventory in 'Data Module Inventory\dtmInventory.pas' {dmInventory: TDataModule},
  frmUni in '..\..\Modul General\Form Template\frmUni.pas' {FormUni},
  frmUniDB in '..\..\Modul General\Form Template\frmUniDB.pas' {FormUniDB},
  frmUniDBEditableEx in '..\..\Modul General\Form Template\frmUniDBEditableEx.pas' {FormUniDBEditableEx},
  frmUniDBNavigator in '..\..\Modul General\Form Template\frmUniDBNavigator.pas' {FormUniDBNavigator},
  frmUniDBNavigatorEx in '..\..\Modul General\Form Template\frmUniDBNavigatorEx.pas' {FormUniDBNavigatorEx},
  frmUniDBPrintableEx in '..\..\Modul General\Form Template\frmUniDBPrintableEx.pas' {FormUniDBPrintableEx},
  frmUniDisplay in '..\..\Modul General\Form Template\frmUniDisplay.pas' {FormUniDisplay},
  frmUniDisplayPeriod in '..\..\Modul General\Form Template\frmUniDisplayPeriod.pas' {FormUniDisplayPeriod},
  frmUniMainMenu in '..\..\Modul General\Form Template\frmUniMainMenu.pas' {FormUniMainMenu},
  frmUniManufacture in '..\..\Modul General\Form Template\frmUniManufacture.pas' {FormUniManufacture},
  frmUniMasterEx in '..\..\Modul General\Form Template\frmUniMasterEx.pas' {FormUniMasterEx},
  frmUniPosition in '..\..\Modul General\Form Template\frmUniPosition.pas' {FormUniPosition},
  frmUniTransactionEx in '..\..\Modul General\Form Template\frmUniTransactionEx.pas' {FormUniTransactionEx},
  frmAbout in '..\..\Modul General\Form About\frmAbout.pas' {fmAbout},
  frmBackupDatabase in '..\..\Modul General\Form Backup Database\frmBackupDatabase.pas' {fmBackupDatabase},
  frmChangePassword in '..\..\Modul General\Form Change Password\frmChangePassword.pas' {fmChangePassword},
  frmCity in '..\..\Modul General\Form City\frmCity.pas' {fmCity},
  frmClosingDate in '..\..\Modul General\Form Closing Date\frmClosingDate.pas' {fmClosingDate},
  frmCOA in '..\..\Modul Accounting\Form COA\frmCOA.pas' {fmCOA},
  frmCompany in '..\..\Modul General\Form Company\frmCompany.pas' {fmCompany},
  frmCountry in '..\..\Modul General\Form Country\frmCountry.pas' {fmCountry},
  frmCurrency in '..\..\Modul General\Form Currency\frmCurrency.pas' {fmCurrency},
  frmDailyKurs in '..\..\Modul General\Form Daily Kurs\frmDailyKurs.pas' {fmDailyKurs},
  frmDepartment in '..\..\Modul General\Form Department\frmDepartment.pas' {fmDepartment},
  frmEmployee in '..\..\Modul General\Form Employee\frmEmployee.pas' {fmEmployee},
  frmExportImportData in '..\..\Modul General\Form Export Import Data\frmExportImportData.pas' {fmExportImportData},
  frmExportReport in '..\..\Modul General\Form Export Report\frmExportReport.pas' {fmExportReport},
  frmImportReport in '..\..\Modul General\Form Import Report\frmImportReport.pas' {fmImportReport},
  frmLogin in '..\..\Modul General\Form Login\frmLogin.pas' {fmLogin},
  frmMaintainceDatabase in '..\..\Modul General\Form Maintaince Database\frmMaintainceDatabase.pas' {fmMaintainceDatabase},
  frmMenuOptions in '..\..\Modul General\Form Menu Options\frmMenuOptions.pas' {fmMenuOptions},
  frmOpenWaiting in '..\..\Modul General\Form Open Waiting\frmOpenWaiting.pas' {fmOpenWaiting},
  frmPosition in '..\..\Modul General\Form Position\frmPosition.pas' {fmPosition},
  frmPreviewFastReport in '..\..\Modul General\Form Preview FastReport\frmPreviewFastReport.pas' {fmPreviewFastReport},
  frmPrintFastReport in '..\..\Modul General\Form Print FastReport\frmPrintFastReport.pas' {fmPrintFastReport},
  frmProvince in '..\..\Modul General\Form Province\frmProvince.pas' {fmProvince},
  frmReportCategory in '..\..\Modul General\Form Report Category\frmReportCategory.pas' {fmReportCategory},
  frmReportDesigner in '..\..\Modul General\Form Report Designer\frmReportDesigner.pas' {fmReportDesigner},
  frmRestoreDatabase in '..\..\Modul General\Form Restore Database\frmRestoreDatabase.pas' {fmRestoreDatabase},
  frmSecurity in '..\..\Modul General\Form Security\frmSecurity.pas' {fmSecurity},
  frmSettingGlobal in '..\..\Modul General\Form Setting Global\frmSettingGlobal.pas' {fmSettingGlobal},
  frmSettingGlobalInventory in '..\..\Modul General\Form Setting Global\frmSettingGlobalInventory.pas' {fmSettingGlobalInventory},
  frmSettingGlobalTimber in '..\..\Modul General\Form Setting Global\frmSettingGlobalTimber.pas' {fmSettingGlobalTimber},
  frmSettingLocal in '..\..\Modul General\Form Setting Local\frmSettingLocal.pas' {fmSettingLocal},
  dtmAccounting in '..\..\Modul Accounting\Data Module Accounting\dtmAccounting.pas' {dmAccounting: TDataModule},
  dtmManufacture in 'Data Module Manufacture\dtmManufacture.pas' {dmManufacture: TDataModule},
  dtmTimber in 'Data Module Timber\dtmTimber.pas' {dmTimber: TDataModule},
  frmBillMaterial in 'Form Bill Material\frmBillMaterial.pas' {fmBillMaterial},
  frmBillMaterialInsert in 'Form Bill Material\frmBillMaterialInsert.pas' {fmBillMaterialInsert},
  frmBillMaterialModify in 'Form Bill Material\frmBillMaterialModify.pas' {fmBillMaterialModify},
  frmChamberIn in 'Form Chamber In\frmChamberIn.pas' {fmChamberIn},
  frmCosting in 'Form Costing\frmCosting.pas' {fmCosting},
  frmCostingPrice in 'Form Costing Price\frmCostingPrice.pas' {fmCostingPrice},
  frmCustomer in 'Form Customer\frmCustomer.pas' {fmCustomer},
  frmCustomerCategory in 'Form Customer Category\frmCustomerCategory.pas' {fmCustomerCategory},
  frmDisplayStock in 'Form Display Stock\frmDisplayStock.pas' {fmDisplayStock},
  frmEngine in 'Form Engine\frmEngine.pas' {fmEngine},
  frmEntryItemBatch in 'Form Entry Item Batch\frmEntryItemBatch.pas' {fmEntryItemBatch},
  frmGrader in 'Form Grader\frmGrader.pas' {fmGrader},
  frmHasilGrade in 'Form Hasil Grade\frmHasilGrade.pas' {fmHasilGrade},
  frmHasilGradeBalok in 'Form Hasil Grade\frmHasilGradeBalok.pas' {fmHasilGradeBalok},
  frmHasilGradeEntry in 'Form Hasil Grade\frmHasilGradeEntry.pas' {fmHasilGradeEntry},
  frmHasilGradeLog in 'Form Hasil Grade\frmHasilGradeLog.pas' {fmHasilGradeLog},
  frmItem in 'Form Item\frmItem.pas' {fmItem},
  frmItemCategory in 'Form Item Category\frmItemCategory.pas' {fmItemCategory},
  frmItemKayu in 'Form Item\frmItemKayu.pas' {fmItemKayu},
  frmKayuMuat in 'Form Kayu Muat\frmKayuMuat.pas' {fmKayuMuat},
  frmKayuMuatBalok in 'Form Kayu Muat\frmKayuMuatBalok.pas' {fmKayuMuatBalok},
  frmKayuMuatEntry in 'Form Kayu Muat\frmKayuMuatEntry.pas' {fmKayuMuatEntry},
  frmKayuMuatLog in 'Form Kayu Muat\frmKayuMuatLog.pas' {fmKayuMuatLog},
  frmKoorGrader in 'Form Koor Grader\frmKoorGrader.pas' {fmKoorGrader},
  frmLHP in 'Form LHP\frmLHP.pas' {fmLHP},
  frmMainMenu in 'Form Main Menu BMI\frmMainMenu.pas' {fmMainMenu},
  frmMaterial in 'Form Material\frmMaterial.pas' {fmMaterial},
  frmOtherTransaction in 'Form Other Transaction\frmOtherTransaction.pas' {fmOtherTransaction},
  frmOutlet in 'Form Outlet\frmOutlet.pas' {fmOutlet},
  frmPenerimaanBarang in 'Form Penerimaan Barang\frmPenerimaanBarang.pas' {fmPenerimaanBarang},
  frmPenerimaanBarangItem in 'Form Penerimaan Barang\frmPenerimaanBarangItem.pas' {fmPenerimaanBarangItem},
  frmPenerimaanBarangKayuBalok in 'Form Penerimaan Barang\frmPenerimaanBarangKayuBalok.pas' {fmPenerimaanBarangKayuBalok},
  frmPenerimaanBarangKayuEntry in 'Form Penerimaan Barang\frmPenerimaanBarangKayuEntry.pas' {fmPenerimaanBarangKayuEntry},
  frmPenerimaanBarangKayuLog in 'Form Penerimaan Barang\frmPenerimaanBarangKayuLog.pas' {fmPenerimaanBarangKayuLog},
  frmPermintaanBahan in 'Form Permintaan Bahan\frmPermintaanBahan.pas' {fmPermintaanBahan},
  frmPermintaanBahanBalok in 'Form Permintaan Bahan\frmPermintaanBahanBalok.pas' {fmPermintaanBahanBalok},
  frmPermintaanBahanLog in 'Form Permintaan Bahan\frmPermintaanBahanLog.pas' {fmPermintaanBahanLog},
  frmPOManufacture in 'Form PO Manufacture\frmPOManufacture.pas' {fmPOManufacture},
  frmPOManufactureBalok in 'Form PO Manufacture\frmPOManufactureBalok.pas' {fmPOManufactureBalok},
  frmPOManufactureItem in 'Form PO Manufacture\frmPOManufactureItem.pas' {fmPOManufactureItem},
  frmPOManufactureLog in 'Form PO Manufacture\frmPOManufactureLog.pas' {fmPOManufactureLog},
  frmPreviewRRAndPO in 'Form Preview RR and PO\frmPreviewRRAndPO.pas' {fmPreviewRRAndPO},
  frmProductionUnit in 'Form Production Unit\frmProductionUnit.pas' {fmProductionUnit},
  frmProject in 'Form Project\frmProject.pas' {fmProject},
  frmPurchaseInvoice in 'Form Purchase Invoice\frmPurchaseInvoice.pas' {fmPurchaseInvoice},
  frmPurchasePrice in 'Form Purchase Price\frmPurchasePrice.pas' {fmPurchasePrice},
  frmPurchasePriceList in 'Form Purchase Price List\frmPurchasePriceList.pas' {fmPurchasePriceList},
  frmRoughSize in 'Form Rough Size\frmRoughSize.pas' {fmRoughSize},
  frmSalePrice in 'Form Sale Price\frmSalePrice.pas' {fmSalePrice},
  frmSalePriceList in 'Form Sale Price List\frmSalePriceList.pas' {fmSalePriceList},
  frmShipping in 'Form Shipping\frmShipping.pas' {fmShipping},
  frmSOManufacture in 'Form SO Manufacture\frmSOManufacture.pas' {fmSOManufacture},
  frmSPK in 'Form SPK\frmSPK.pas' {fmSPK},
  frmSPKTimber in 'Form SPK\frmSPKTimber.pas' {fmSPKTimber},
  frmTableLog in 'Form Table Log\frmTableLog.pas' {fmTableLog},
  frmTallyMan in 'Form TallyMan\frmTallyMan.pas' {fmTallyMan},
  frmTallySheetGrade in 'Form Tally Sheet Grade\frmTallySheetGrade.pas' {fmTallySheetGrade},
  frmVendor in 'Form Vendor\frmVendor.pas' {fmVendor},
  frmVendorCategory in 'Form Vendor Category\frmVendorCategory.pas' {fmVendorCategory},
  frmWarehouse in 'Form Warehouse\frmWarehouse.pas' {fmWarehouse};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Zetron Manufacture Timber';
  untConstanta.FProgramId := untConstanta.PROGRAM_ID_MANUFACTORY_TIM;
  untConstanta.FProgramName := untConstanta.PROGRAM_NAME_MANUFACTORY_TIM;
  Application.CreateForm(TdmGlobal, dmGlobal);
  Application.CreateForm(TdmInventory, dmInventory);
  Application.CreateForm(TdmManufacture, dmManufacture);
  Application.CreateForm(TdmAccounting, dmAccounting);
  Application.CreateForm(TdmTimber, dmTimber);
  Application.CreateForm(TfmMainMenu, fmMainMenu);
  Application.Run;
end.



